import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
from datetime import datetime

SIZE = 4000
DPI = 300
DATE = datetime.now().strftime("%d%m%Y")

SCRIPT_DIR = Path(__file__).resolve().parent
OUTPUT_DIR = SCRIPT_DIR.parent / "output"
JPG_DIR = OUTPUT_DIR / "jpg"
SVG_DIR = OUTPUT_DIR / "svg"
JPG_DIR.mkdir(parents=True, exist_ok=True)
SVG_DIR.mkdir(parents=True, exist_ok=True)


def setup_ax():
    fig, ax = plt.subplots(figsize=(SIZE / DPI, SIZE / DPI), dpi=DPI)
    fig.subplots_adjust(left=0, right=1, top=1, bottom=0)
    ax.set_facecolor("white")
    ax.set_xlim(-5, 105)
    ax.set_ylim(-5, 105)
    ax.set_aspect("equal")
    ax.axis("off")
    return fig, ax


def save(fig, name):
    jpg_path = JPG_DIR / f"{name} {DATE}.jpg"
    svg_path = SVG_DIR / f"{name} {DATE}.svg"
    fig.savefig(jpg_path, dpi=DPI, pad_inches=0, facecolor="white")
    fig.savefig(svg_path, format="svg", pad_inches=0, facecolor="white")
    plt.close(fig)
    print(f"Tersimpan: {jpg_path} | {svg_path}")


def draw():
    """
    Sierpinski Carpet Menger Sponge Fractal.
    A 2D cross-section of a Menger sponge fractal (Sierpinski carpet),
    generated by recursively subdividing a square into 9 squares and removing the center.
    """
    fig, ax = setup_ax()

    import matplotlib.patches as patches

    def draw_carpet(x, y, size, depth):
        if depth == 0:
            # Base case: draw the solid square
            rect = patches.Rectangle((x, y), size, size, 
                                     linewidth=0.5, edgecolor='none', facecolor='black')
            ax.add_patch(rect)
        else:
            sub_size = size / 3.0
            for i in range(3):
                for j in range(3):
                    # Skip the center square
                    if i == 1 and j == 1:
                        # Draw an outline for the removed center to give it texture
                        rect = patches.Rectangle((x + j*sub_size, y + i*sub_size), sub_size, sub_size, 
                                     linewidth=1.0, edgecolor='black', facecolor='white', hatch='////')
                        ax.add_patch(rect)
                        continue
                        
                    draw_carpet(x + j*sub_size, y + i*sub_size, sub_size, depth - 1)

    # We draw a few large carpets to cover the viewport
    carpet_size = 110.0
    
    # We can center one huge carpet
    draw_carpet(50 - carpet_size/2, 50 - carpet_size/2, carpet_size, 4)

    save(fig, "abstract grid tessellation sierpinski carpet menger sponge fractal pattern black white texture")


if __name__ == "__main__":
    draw()
