import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
from datetime import datetime

SIZE = 4000
DPI = 300
SEED = 42
DATE = datetime.now().strftime("%d%m%Y")

SCRIPT_DIR = Path(__file__).resolve().parent
OUTPUT_DIR = SCRIPT_DIR.parent / "output"
JPG_DIR = OUTPUT_DIR / "jpg"
SVG_DIR = OUTPUT_DIR / "svg"
JPG_DIR.mkdir(parents=True, exist_ok=True)
SVG_DIR.mkdir(parents=True, exist_ok=True)

np.random.seed(SEED)


def setup_ax():
    fig, ax = plt.subplots(figsize=(SIZE / DPI, SIZE / DPI), dpi=DPI)
    fig.subplots_adjust(left=0, right=1, top=1, bottom=0)
    ax.set_facecolor("white")
    ax.set_xlim(-50, 50)
    ax.set_ylim(-50, 50)
    ax.set_aspect("equal")
    ax.axis("off")
    return fig, ax


def save(fig, name):
    jpg_path = JPG_DIR / f"{name} {DATE}.jpg"
    svg_path = SVG_DIR / f"{name} {DATE}.svg"
    fig.savefig(jpg_path, dpi=DPI, pad_inches=0, facecolor="white")
    fig.savefig(svg_path, format="svg", pad_inches=0, facecolor="white")
    plt.close(fig)
    print(f"Tersimpan: {jpg_path} | {svg_path}")


def generate():
    """Wild: Moiré generated by two hexagonal grids offset by 5 degrees from each other."""
    fig, ax = setup_ax()

    def draw_hex_grid(ax, angle_deg, spacing, lw):
        angle = np.radians(angle_deg)
        # Three families of lines for a hexagonal grid
        families = [0, 60, 120]
        for fam in families:
            fam_angle = np.radians(fam) + angle
            nx = np.cos(fam_angle)
            ny = np.sin(fam_angle)

            for d in np.arange(-100, 100, spacing):
                # Line: nx*x + ny*y = d
                perp_x = d * nx
                perp_y = d * ny
                tangent_x = -ny
                tangent_y = nx
                x0 = perp_x - 80 * tangent_x
                x1 = perp_x + 80 * tangent_x
                y0 = perp_y - 80 * tangent_y
                y1 = perp_y + 80 * tangent_y
                ax.plot([x0, x1], [y0, y1], color="black", linewidth=lw)

    draw_hex_grid(ax, 0, 6.0, 1.0)
    draw_hex_grid(ax, 5, 6.0, 1.0)

    save(fig, "abstract optical moire hexagonal grid dual offset pattern black white texture")


if __name__ == "__main__":
    generate()
